---
title: "List column type in data.frame"
# output: html_notebook
output:
  html_document:
    df_print: paged
    theme: united # https://bootswatch.com/3/
    highlight: tango # default, tango, pygments, kate, monochrome, espresso, zenburn, haddock, and textmate
---
```{r include=FALSE}
library(tidyverse)
library(lobstr)  #, quietly = T
```


tibble이나, data.frame 의 경우, 컬럼 type 이 list 인 경우가 존재함.

```{r}
df = tibble(
  x = 1:3,
  y = list(1:2, 1:3, 1:4)
)
df
```



```{r eval=FALSE}
ref(df)
# █ [1:0x7f948dbb90c8] <tibble> 
# ├─x = [2:0x7f948d629ef8] <int> 
# └─y = █ [3:0x7f948a7ebb68] <list> 
#       ├─[4:0x7f948d628438] <int> 
#       ├─[5:0x7f948d624608] <int> 
#       └─[6:0x7f948d6246e8] <int> 
```

```{r}
str(df)
```

만약에 저 y 컬럼 타입이 리스트를 담게 되다보니, 자유로운 값들이 리스크 안에 입력이 가능하다.

저 list 안에 있는 vector 들 중에, 첫번째 인자값들만 추출해서 다른 필드로 만드려면, map 함수를 이용해서 추출해야 한다. (lapply, sapply 등도 가능.)

```{r}
df %>% mutate(y_first = map(y, first))
df %>% mutate(y_first = lapply(y, first))
```


\
\



여전히 list 결과처럼 보이므로, vector 로 변경하면,

```{r}
df %>% mutate(y_first = map_dbl(y, dplyr::first))
df %>% mutate(y_first = unlist(map(y, dplyr::first)))
df %>% mutate(y_first = sapply(y, dplyr::first))
df %>% mutate(y_first = unlist(lapply(y, dplyr::first)))
```


각 element 에서, n 번째 값을 추출하려면, dplyr::nth 함수를 사용하면 된다.  
```{r}
df %>% mutate(y1 = map_dbl(y, dplyr::nth, 2))
```
마지막 요소를 추출하려면, dplyr::last 를 사용.
```{r}
df %>% mutate(y1 = map_dbl(y, dplyr::last))
```




